packages:
  - packages/*
  - configs/*

catalog:
  '@types/lodash-es': ^4.17.12
  '@types/node': ^24
  chalk: ^5.6.2
  lodash-es: ^4.17.23
  neverthrow: ^8.2.0
  oxlint: 1.56.0
  pino: ^10.3.1
  type-fest: ^5.5.0
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  xstate: ^5.28.0
  zod: ^4.3.6

catalogMode: prefer
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
