import type { AgentPresetConfig } from './agent-preset.config.js';
import { claudeAgentPresetConfig } from './claude-agent-preset.config.js';
import { codexAgentPresetConfig } from './codex-agent-preset.config.js';
import { cursorAgentPresetConfig } from './cursor-agent-preset.config.js';

/**
 * Centralized preset config registry.
 *
 * All production code should read agent paths and file names from this module
 * instead of inlining per-agent strings inside behaviors.
 *
 * Keep this as the single source of truth so sync behaviors stay fully generic.
 */
const presetConfigByAgent: Record<string, AgentPresetConfig> = {
  claude: claudeAgentPresetConfig,
  codex: codexAgentPresetConfig,
  cursor: cursorAgentPresetConfig,
};

/** Synthesizes an `AgentPresetConfig` from `agentName` when no built-in preset exists (custom agents). */
function buildFallbackAgentPresetConfig(agentName: string): AgentPresetConfig {
  return {
    CONSTANTS: {
      AGENT_MARKETPLACE_FILE: `.${agentName}/marketplace.json`,
      AGENT_MARKETPLACE_SOURCE_FORMAT: 'prefixed',
      AGENT_NAME: agentName,
      AGENT_RULES_DIR: `.${agentName}/rules`,
      AGENT_RULES_MARKDOWN_FRONTMATTER: '---\nalwaysApply: true\n---\n\n',
      AGENT_SETTINGS_FILE: `.${agentName}/settings.json`,
      get AGENT_SETTINGS_MANIFEST_KEY() {
        return this.AGENT_NAME;
      },
      AGENT_SKILLS_DIR: `.${agentName}/skills`,
      MARKDOWN_CONTEXT_TARGET_FILE_NAME: `${agentName.toUpperCase()}.md`,
      MARKDOWN_SECTION_FILE: 'AGENTS.override.md',
      MARKDOWN_SECTION_HEADING: 'packages (generated by clankgsters)',
      PLUGIN_MANIFEST_DIR: `.${agentName}-plugin`,
      PLUGINS_DIRECTORY_TARGET_ROOT: `.${agentName}`,
      SKILLS_DIRECTORY_SYNC_ENABLED: false,
    },
  };
}

export const agentPresetConfigs = {
  /** Built-in presets keyed by agent name (`claude`, `codex`, `cursor`). */
  byAgent: presetConfigByAgent,
  /** Returns the preset for `agentName`, or a fallback from {@link buildFallbackAgentPresetConfig} when unknown. */
  resolve(agentName: string): AgentPresetConfig {
    return presetConfigByAgent[agentName] ?? buildFallbackAgentPresetConfig(agentName);
  },
};
