import type { AgentPresetConfig } from './agent-preset.config.js';

/** Codex preset constants as a single source of truth. */
export const codexAgentPresetConfig = {
  CONSTANTS: {
    AGENT_MARKETPLACE_FILE: '.codex/marketplace.json',
    AGENT_MARKETPLACE_SOURCE_FORMAT: 'prefixed',
    AGENT_NAME: 'codex',
    AGENT_RULES_DIR: '.codex/rules',
    AGENT_RULES_MARKDOWN_FRONTMATTER: undefined,
    AGENT_RULES_SYNC_MANIFEST: undefined,
    AGENT_SETTINGS_FILE: '.codex/settings.json',
    get AGENT_SETTINGS_MANIFEST_KEY() {
      return this.AGENT_NAME;
    },
    AGENT_SKILLS_DIR: '.codex/skills',
    GITIGNORE_COMMENT: '\n# clankgsters-sync: symlinked from CLANK.md for Codex\n',
    get GITIGNORE_ENTRY() {
      return this.MARKDOWN_CONTEXT_TARGET_FILE_NAME;
    },
    MARKDOWN_CONTEXT_TARGET_FILE_NAME: 'AGENTS.md',
    MARKDOWN_SECTION_FILE: 'AGENTS.override.md',
    MARKDOWN_SECTION_HEADING: 'packages (generated by clankgsters)',
    PLUGIN_MANIFEST_DIR: '.codex-plugin',
    SKILLS_DIRECTORY_SYNC_ENABLED: false,
  },
} as const satisfies AgentPresetConfig;
