import type { ClankgsterAgentConfig } from '../../configs/clankgster-config.schema.js';
import type { MarkdownSectionSyncPresetOptions } from '../../sync-behaviors/presets/markdown-section-sync-preset.js';
import type { MarkdownContextSyncPresetOptions } from '../../sync-behaviors/presets/markdown-symlink-sync-preset.js';
import type { SkillsDirectorySyncPresetOptions } from '../../sync-behaviors/presets/skills-directory-sync-preset.js';
import { defineAgentConstants } from './define-agent-constants.js';

/** Codex preset constants consumed by default behavior option wiring. */
export const codexAgentPresetConstants = defineAgentConstants({
  COMMON: {
    AGENT_NAME: 'codex',
    AGENT_MARKDOWN_CONTEXT_FILE_NAME: 'AGENTS.md',
    AGENT_PLUGIN_MANIFEST_DIR: null,
  },
  BEHAVIORS: {
    MarkdownSectionSyncPreset: {
      markdownContextOverrideFileName: 'AGENTS.override.md',
      sectionHeading: 'packages (generated by clankgster)',
    } satisfies MarkdownSectionSyncPresetOptions,
    MarkdownContextSyncPreset: {
      targetFile: 'AGENTS.md',
      gitignoreComment: '\n# clankgster-sync: symlinked from CLANK.md for Codex\n',
      gitignoreEntry: 'AGENTS.md',
    } satisfies MarkdownContextSyncPresetOptions,
    SkillsDirectorySyncPreset: {
      nativeSkillsDir: '.agents/skills',
      skillsDirectorySyncEnabled: false,
    } satisfies SkillsDirectorySyncPresetOptions,
  },
});

/** Default Codex preset behaviors for sync runs. */
export const codexAgentPreset: ClankgsterAgentConfig = {
  enabled: true,
  behaviors: [
    {
      enabled: true,
      behaviorName: 'MarkdownContextSyncPreset',
      options: codexAgentPresetConstants.BEHAVIORS.MarkdownContextSyncPreset,
    },
    {
      enabled: true,
      behaviorName: 'SkillsDirectorySyncPreset',
      options: codexAgentPresetConstants.BEHAVIORS.SkillsDirectorySyncPreset,
    },
    {
      enabled: true,
      behaviorName: 'MarkdownSectionSyncPreset',
      options: codexAgentPresetConstants.BEHAVIORS.MarkdownSectionSyncPreset,
    },
  ],
};
