import { err, ok, type Result } from 'neverthrow';
import path from 'node:path';
import { markdownSection } from '../../../common/markdown-section.js';
import { pathHelpers } from '../../../common/path-helpers.js';
import { SyncBehaviorBase, type SyncBehaviorRunContext } from '../sync-behavior-base.js';

/** Syncs marketplace plugin links into a managed section of the root context markdown file. */
export class MarkdownSectionSyncPreset extends SyncBehaviorBase {
  override syncRun(context: SyncBehaviorRunContext): Result<void, Error> {
    const options = {
      agentsFile: 'AGENTS.override.md',
      sectionHeading: 'packages (generated by clankgsters)',
      ...(context.behaviorConfig.options as Record<string, unknown>),
    };
    const outputRootResolved = path.resolve(context.outputRoot);
    const defaultMarkdownRel = context.resolvedConfig.sourceDefaults.markdownContextFileName;
    const markdownContextPath =
      typeof options.agentsFile === 'string' ? options.agentsFile : defaultMarkdownRel;
    const candidateResolved = path.resolve(outputRootResolved, markdownContextPath);
    let filePath: string;
    if (pathHelpers.isResolvedPathUnderRoot(outputRootResolved, candidateResolved)) {
      filePath = candidateResolved;
    } else {
      const fallbackResolved = path.resolve(outputRootResolved, defaultMarkdownRel);
      if (pathHelpers.isResolvedPathUnderRoot(outputRootResolved, fallbackResolved)) {
        filePath = fallbackResolved;
      } else {
        return err(
          new Error(
            `markdownSectionSync: resolved path escapes outputRoot (${JSON.stringify(markdownContextPath)} and default ${JSON.stringify(defaultMarkdownRel)})`
          )
        );
      }
    }
    const heading =
      typeof options.sectionHeading === 'string' && options.sectionHeading.length > 0
        ? options.sectionHeading
        : 'packages (generated by clankgsters)';
    if (context.mode === 'clear' || context.behaviorConfig.enabled === false) {
      return markdownSection.removeSection(filePath, heading);
    }

    const lines: string[] = [];
    for (const marketplace of context.discoveredMarketplaces) {
      const plugins = marketplace.plugins.filter(
        (plugin) => plugin.manifests[context.agentName] === true
      );
      if (plugins.length === 0) continue;
      lines.push(`### \`${marketplace.relativePath}\` marketplace`, '');
      for (const plugin of plugins) {
        lines.push(`- [${plugin.manifestName ?? plugin.name}](./${plugin.relativePath})`);
      }
      lines.push('');
    }

    const result = markdownSection.replaceOrAddSection(filePath, heading, lines.join('\n').trim());
    if (result.isErr()) return result;
    context.registerManifestEntry(context.agentName, context.behaviorConfig.behaviorName, {
      options,
    });
    return ok(undefined);
  }
}
