import { err, ok, type Result } from 'neverthrow';
import path from 'node:path';
import { z } from 'zod';
import { markdownSection } from '../../../common/markdown-section.js';
import { pathHelpers } from '../../../common/path-helpers.js';
import { SyncBehaviorBase, type SyncBehaviorRunContext } from '../sync-behavior-base.js';

const markdownSectionSyncPresetOptionsSchema = z.looseObject({
  markdownContextOverrideFileName: z.string().min(1).optional(),
  sectionHeading: z.string().min(1).optional(),
});

/** Typed options for `MarkdownSectionSyncPreset`. */
export interface MarkdownSectionSyncPresetOptions {
  /** Override target markdown file that receives generated marketplace section; defaults to resolved `sourceDefaults.markdownContextFileName`. */
  markdownContextOverrideFileName?: string;
  /** Section heading to replace/add in the target markdown file. */
  sectionHeading?: string;
}

/** Syncs marketplace plugin links into a managed section of the root context markdown file. */
export class MarkdownSectionSyncPreset extends SyncBehaviorBase {
  override syncRun(context: SyncBehaviorRunContext): Result<void, Error> {
    const parsedOptions = markdownSectionSyncPresetOptionsSchema.safeParse(
      context.behaviorConfig.options
    );
    const defaultMarkdownRel = context.resolvedConfig.sourceDefaults.markdownContextFileName;
    const resolvedOptions = {
      markdownContextOverrideFileName: defaultMarkdownRel,
      sectionHeading: 'packages (generated by clankgsters)',
      ...(parsedOptions.success ? parsedOptions.data : {}),
    };
    const outputRootResolved = path.resolve(context.outputRoot);
    const markdownContextPath = resolvedOptions.markdownContextOverrideFileName;
    const candidateResolved = path.resolve(outputRootResolved, markdownContextPath);
    let filePath: string;
    if (pathHelpers.isResolvedPathUnderRoot(outputRootResolved, candidateResolved)) {
      filePath = candidateResolved;
    } else {
      const fallbackResolved = path.resolve(outputRootResolved, defaultMarkdownRel);
      if (pathHelpers.isResolvedPathUnderRoot(outputRootResolved, fallbackResolved)) {
        filePath = fallbackResolved;
      } else {
        return err(
          new Error(
            `markdownSectionSync: resolved path escapes outputRoot (${JSON.stringify(markdownContextPath)} and default ${JSON.stringify(defaultMarkdownRel)})`
          )
        );
      }
    }
    const heading =
      typeof resolvedOptions.sectionHeading === 'string' &&
      resolvedOptions.sectionHeading.length > 0
        ? resolvedOptions.sectionHeading
        : 'packages (generated by clankgsters)';
    if (context.mode === 'clear' || context.behaviorConfig.enabled === false) {
      return markdownSection.removeSection(filePath, heading);
    }

    const lines: string[] = [];
    for (const marketplace of context.discoveredMarketplaces) {
      const plugins = marketplace.plugins.filter(
        (plugin) => plugin.manifests[context.agentName] === true
      );
      if (plugins.length === 0) continue;
      lines.push(`### \`${marketplace.relativePath}\` marketplace`, '');
      for (const plugin of plugins) {
        lines.push(`- [${plugin.manifestName ?? plugin.name}](./${plugin.relativePath})`);
      }
      lines.push('');
    }

    const result = markdownSection.replaceOrAddSection(filePath, heading, lines.join('\n').trim());
    if (result.isErr()) return result;
    context.registerManifestEntry(context.agentName, context.behaviorConfig.behaviorName, {
      options: resolvedOptions,
    });
    return ok(undefined);
  }
}
