import { ok, type Result } from 'neverthrow';
import path from 'node:path';
import { markdownSection } from '../../../common/markdown-section.js';
import { SyncBehaviorBase, type SyncBehaviorRunContext } from '../sync-behavior-base.js';

/** Syncs marketplace plugin links into a managed section of the root context markdown file. */
export class MarkdownSectionSyncPreset extends SyncBehaviorBase {
  override syncRun(context: SyncBehaviorRunContext): Result<void, Error> {
    const options = {
      agentsFile: 'AGENTS.override.md',
      sectionHeading: 'packages (generated by clankgsters)',
      ...(context.behaviorConfig.options as Record<string, unknown>),
    };
    const markdownContextPath =
      typeof options.agentsFile === 'string'
        ? options.agentsFile
        : context.resolvedConfig.sourceDefaults.markdownContextFileName;
    const filePath = path.join(context.outputRoot, markdownContextPath);
    const heading =
      typeof options.sectionHeading === 'string' && options.sectionHeading.length > 0
        ? options.sectionHeading
        : 'packages (generated by clankgsters)';
    if (context.mode === 'clear' || context.behaviorConfig.enabled === false) {
      return markdownSection.removeSection(filePath, heading);
    }

    const lines: string[] = [];
    for (const marketplace of context.discoveredMarketplaces) {
      const plugins = marketplace.plugins.filter(
        (plugin) => plugin.manifests[context.agentName] === true
      );
      if (plugins.length === 0) continue;
      lines.push(`### \`${marketplace.relativePath}\` marketplace`, '');
      for (const plugin of plugins) {
        lines.push(`- [${plugin.manifestName ?? plugin.name}](./${plugin.relativePath})`);
      }
      lines.push('');
    }

    const result = markdownSection.replaceOrAddSection(filePath, heading, lines.join('\n').trim());
    if (result.isErr()) return result;
    context.registerManifestEntry(context.agentName, context.behaviorConfig.behaviorName, {
      options,
    });
    return ok(undefined);
  }
}
